development:
  access_key_id: "ACCESS_KEY"
  secret_access_key: "SECRET_ACCESS_KEY"
  region: "REGION_NAME"
  bucket: "BUKCET_NAME"
  default_key: "ror-postgres-haml"
test:
  access_key_id: "ACCESS_KEY"
  secret_access_key: "SECRET_ACCESS_KEY"
  region: "REGION_NAME"
  bucket: "BUKCET_NAME"
  default_key: "ror-postgres-haml"
production:
  access_key_id: "ACCESS_KEY"
  secret_access_key: "SECRET_ACCESS_KEY"
  region: "REGION_NAME"
  bucket: "BUKCET_NAME"
  default_key: "ror-postgres-haml"
